.TH PMB 1 2022-10-23 GNU

.SH NAME
pmb \- Poor Man's Bookmark

.SH SYNOPSIS
.B pmb

.SH DESCRIPTION
.B pmb
is a small program to manage bookmarks.

.SH OPTIONS
.TP
.B \-h, \-\-help
show help message

.SH AUTHOR
Original Author: neoncortex <myshell.org@gmail.com>
Fork Author: zockerfreunde03/z0gg3r <zocker@10zen.eu>
